### PR TITLE
Fix null dereference caught by the static analyzer

### PR DESCRIPTION
**Pull request by ianegordon**

### CODE REVIEW

**Comment by jverkoey** [comment]
What was the warning and why did this fix it?

**Comment by ianegordon** [comment]
Access to instance variable '_transition' results in a dereference of a null pointer (loaded from variable 'self').

By moving the check inside the if (self) block we are sure to have a self pointer.  

I think / suspect this may be to catch if fallbackForTransition: fails which only gets called if (self), so moving inside the block should not change behavior.  We might consider adding an NSAssert or throwing an exception if we don't expect to ever get in this state.

**Comment by ianegordon** [comment]
For context, this was discovered while looking at MDC-iOS : Add Masked Transition component PR.
https://github.com/material-components/material-components-ios/pull/1513

**Comment by jverkoey** [comment]
Awesome! Thanks :D

**Review by jverkoey — APPROVED** [review]

**Pull request merged**
